spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:gridcapa}
    password: ${RABBITMQ_PASSWORD:gridcapa}
    template:
      reply-timeout: 6000000

cse-valid-publication:
  filenames:
    ttc-adjustment: "TTC_Adjustment_(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})_(ID|2D)[1-7](_Final)?_CSE(?<version>[0-9]{1,2}).xml"
    ttc-validation: "'TTC_RTEValidation_'yyyyMMdd'_%s'e'_(?<version>[0-9]{1,2}).xml'"
    crac: "(?<year>[0-9]{4})(?<month>[0-9]{2})(?<day>[0-9]{2})_(?<hour>[0-9]{2})(?<minute>[0-9]{2})_([0-9]{2}|2D)[1-7]_CRAC_FR(?<version>[0-9]{1,2}).xml"
  amqp:
    queue-name: cse-valid-requests
    expiration: 60000
  whitelist:
    - http://localhost:9000
    - http://minio:9000

cse-valid-runner:
  amqp:
    queue-name: cse-valid-requests
    expiration: 60000

minio-adapter:
  bucket: gridcapa
  base-path: CSE/VALID
  access-key: gridcapa
  secret-key: gridcapa
  url: http://localhost:9000/

server:
  port: 9090